Repository FocusStartSpb/Map, pull requests merged in 2020-01, with the labels that each got.

#81 (AKA-48) Добавил тактильный отклик при падении пинов
  Map/Scenes/Map scene/MapViewController.swift
Labels: bug, enhancement

#98 (AKA-62) Данные о посещении при создании / редактировании smartTarget`а
  Map/Business layer/Models/SmartTarget.swift
  Map/Business layer/UserPreferences.swift
  Map/Extensions/UIViewController+Extension.swift
  Map/Scenes/Map scene/MapInteractor.swift
  Map/Scenes/Map scene/MapPresenter.swift
  Map/Scenes/Map scene/MapViewController.swift
  Map/Scenes/Settings scene/Cells/RangeSliderTableViewCell.swift
  Map/Supporting files/Info.plist
Labels: bug, enhancement

#96 (AKA-63) Создал README.md
  README.md
Labels: enhancement

#100 (AKA-61) Фиксы анимаций
  Map/Extensions/UIViewController+Extension.swift
  Map/Scenes/Map scene/MapInteractor.swift
  Map/Scenes/Map scene/MapModels.swift
  Map/Scenes/Map scene/MapPresenter.swift
  Map/Scenes/Map scene/MapViewController.swift
  Map/Supporting files/AppDelegate.swift
Labels: bug

#108 (AKA-67) Исправления багов и вылетов связанных с обновлением при переходе между вкладками на табБаре
  Map/Business layer/Models/SmartTarget.swift
  Map/Business layer/Models/SmartTargetCollection.swift
  Map/Business layer/SceneBuilder.swift
  Map/Scenes/Map scene/MapInteractor.swift
  Map/Scenes/Map scene/MapModels.swift
  Map/Scenes/Map scene/MapPresenter.swift
  Map/Scenes/Map scene/MapRouter.swift
  Map/Scenes/Map scene/MapViewController.swift
  Map/Scenes/Smart target list scene/Detail target scene/DetailTargetPresenter.swift
  Map/Scenes/Smart target list scene/Detail target scene/DetailTargetViewController.swift
  Map/Scenes/Smart target list scene/SmartTargetListInteractor.swift
  Map/Scenes/Smart target list scene/SmartTargetListModels.swift
  Map/Scenes/Smart target list scene/SmartTargetListPresenter.swift
  Map/Scenes/Smart target list scene/SmartTargetListRouter.swift
  Map/Scenes/Smart target list scene/SmartTargetListViewController.swift
  Map/Supporting files/AppDelegate.swift
Labels: bug

#113 (AKA-64) Редактирование в детэйл контроллере
  Map.xcodeproj/project.pbxproj
  Map/Business layer/SceneBuilder.swift
  Map/Scenes/Smart target list scene/Detail target scene/DetailTargetPresenter.swift
  Map/Scenes/Smart target list scene/Detail target scene/DetailTargetViewController+MKMapViewDelegate.swift
  Map/Scenes/Smart target list scene/Detail target scene/DetailTargetViewController.swift
  Map/Scenes/Smart target list scene/SmartTargetListInteractor.swift
  Map/Scenes/Smart target list scene/SmartTargetListPresenter.swift
  Map/Scenes/Smart target list scene/SmartTargetListRouter.swift
Labels: enhancement

#114 (AKA-57) Вынес расширения в отдельные файлы, создал файл с константам…
  Map.xcodeproj/project.pbxproj
  Map/Business layer/Constants.swift
  Map/Business layer/UserPreferences.swift
  Map/Scenes/Map scene/MapViewController+MKMapViewDelegate.swift
  Map/Scenes/Map scene/MapViewController+MapDisplayLogic.swift
  Map/Scenes/Map scene/MapViewController+NotificationCenter.swift
  Map/Scenes/Map scene/MapViewController+NotificationServiceDelegate.swift
  Map/Scenes/Map scene/MapViewController+UITabBarControllerDelegate.swift
  Map/Scenes/Map scene/MapViewController.swift
  Map/Views/SmartTargetMenu.swift
Labels: enhancement

#116 (AKA-68) Дизайн контроллера настроек
  Map/Business layer/Constants.swift
  Map/Business layer/SceneBuilder.swift
  Map/Business layer/UserPreferences.swift
  Map/Business layer/Workers/SettingsWorker.swift
  Map/Extensions/UserPreferences.MeasuringSystem+Extension.swift
  Map/Scenes/Map scene/MapInteractor.swift
  Map/Scenes/Map scene/MapModels.swift
  Map/Scenes/Map scene/MapPresenter.swift
  Map/Scenes/Map scene/MapViewController+MapDisplayLogic.swift
  Map/Scenes/Map scene/MapViewController.swift
  Map/Scenes/Settings scene/Cells/RangeSliderTableViewCell.swift
  Map/Scenes/Settings scene/Cells/SegmentedControlTableViewCell.swift
  Map/Scenes/Settings scene/Cells/SwitchTableViewCell.swift
  Map/Scenes/Settings scene/SettingsInteractor.swift
  Map/Scenes/Settings scene/SettingsModels.swift
  Map/Scenes/Settings scene/SettingsPresenter.swift
  Map/Scenes/Settings scene/SettingsViewController.swift
  Map/Scenes/Settings scene/Workers/SettingsSceneWorker.swift
  Map/Views/SmartTargetMenu.swift
Labels: bug, enhancement

#119 (AKA-50) Применение настроек к сцене с таблицей
  Map/Business layer/SceneBuilder.swift
  Map/Scenes/Map scene/MapViewController+NotificationCenter.swift
  Map/Scenes/Map scene/MapViewController.swift
  Map/Scenes/Smart target list scene/Detail target scene/DetailTargetViewController+MKMapViewDelegate.swift
  Map/Scenes/Smart target list scene/SmartTargetListInteractor.swift
  Map/Scenes/Smart target list scene/SmartTargetListModels.swift
  Map/Scenes/Smart target list scene/SmartTargetListPresenter.swift
  Map/Scenes/Smart target list scene/SmartTargetListViewController.swift
Labels: enhancement

#117 (AKA-58) Окрашивание круга в зависимости от положения юзера
  Map/Business layer/Constants.swift
  Map/Scenes/Map scene/MapViewController+MKMapViewDelegate.swift
  Map/Scenes/Map scene/MapViewController+MapDisplayLogic.swift
  Map/Scenes/Map scene/MapViewController.swift
  Map/Scenes/Settings scene/SettingsViewController.swift
  Map/Scenes/Smart target list scene/Detail target scene/DetailTargetViewController.swift
  Map/Views/Range slider/RangeSlider.swift
Labels: enhancement

#123 (АКА-71) Пофиксил кнопку Редактирования в детейле
  Map/Scenes/Smart target list scene/Detail target scene/DetailTargetViewController.swift
Labels: bug

#124 (AKA-70) Изменение радиуса в Детэйл сцене
  Map/Business layer/Constants.swift
  Map/Business layer/SceneBuilder.swift
  Map/Scenes/Map scene/MapViewController+MapDisplayLogic.swift
  Map/Scenes/Smart target list scene/Detail target scene/DetailTargetPresenter.swift
  Map/Scenes/Smart target list scene/Detail target scene/DetailTargetViewController+MKMapViewDelegate.swift
  Map/Scenes/Smart target list scene/Detail target scene/DetailTargetViewController.swift
  Map/Scenes/Smart target list scene/Detail target scene/View/Slider+EditableAddressView.swift
  Map/Views/SmartTargetMenu.swift
Labels: enhancement

#125 (AKA-14) Рефакторинг
  Map.xcodeproj/project.pbxproj
  Map/Business layer/Alerts.swift
  Map/Business layer/Constants.swift
  Map/Business layer/SceneBuilder.swift
  Map/Business layer/Workers/NotificationWorker.swift
  Map/Extensions/Array+Difference.swift
  Map/Extensions/CLLocationCoordinate2D+Extension.swift
  Map/Extensions/Formatter+Extension.swift
  Map/Extensions/UIColor+Adjust.swift
  Map/Extensions/UILabel+TextAnimation.swift
  Map/Extensions/UserPreferences.MeasuringSystem+Extension.swift
  Map/Scenes/Map scene/MapInteractor.swift
  Map/Scenes/Map scene/MapRouter.swift
  Map/Scenes/Map scene/MapViewController+MKMapViewDelegate.swift
  Map/Scenes/Map scene/MapViewController+MapDisplayLogic.swift
  Map/Scenes/Map scene/MapViewController+NotificationCenter.swift
  Map/Scenes/Map scene/MapViewController+UITabBarControllerDelegate.swift
  Map/Scenes/Map scene/MapViewController.swift
  Map/Scenes/Smart target list scene/SmartTargetListRouter.swift
  Map/Scenes/Smart target list scene/SmartTargetListViewController.swift
  Map/Scenes/TabBarController/TabBarController.swift
  Map/Supporting files/AppDelegate.swift
  Map/Views/SmartTargetMenu.swift
Labels: bug, improvement

#128 (AKA-73) Адаптация высоты меню
  Map/Extensions/UILabel+TextAnimation.swift
  Map/Scenes/Map scene/MapViewController.swift
  Map/Views/SmartTargetMenu.swift
Labels: enhancement

#130 (AKA-74) Улучшения кода
  Map/Business layer/Models/MenuAction.swift
  Map/Business layer/Models/SmartTargetAnnotation.swift
  Map/Business layer/Services/NotificationService.swift
  Map/Business layer/Workers/DataBaseWorker.swift
  Map/Business layer/Workers/NotificationWorker.swift
  Map/Extensions/Array+Difference.swift
  Map/Scenes/Map scene/MapInteractor.swift
  Map/Scenes/Map scene/MapPresenter.swift
  Map/Scenes/Map scene/MapViewController+NotificationCenter.swift
  Map/Scenes/Smart target list scene/SmartTargetListInteractor.swift
  Map/Scenes/Smart target list scene/SmartTargetListRouter.swift
  Map/Scenes/Smart target list scene/SmartTargetListViewController.swift
Labels: improvement

#134 (AKA-76) Фиксы связанные с багами при удалением ячеек
  Map/Scenes/Smart target list scene/SmartTargetListInteractor.swift
  Map/Scenes/Smart target list scene/SmartTargetListModels.swift
  Map/Scenes/Smart target list scene/SmartTargetListPresenter.swift
  Map/Scenes/Smart target list scene/SmartTargetListViewController.swift
Labels: bug

#137 (AKA-77) Анимация исчезновения меню
  Map/Scenes/Map scene/MapViewController+NotificationCenter.swift
  Map/Scenes/Map scene/MapViewController.swift
  Map/Views/SmartTargetMenu.swift
Labels: bug

#136 (АКА-75) Пофиксил конфликт констрейнтов у ячеек
  Map/Business layer/Constants.swift
  Map/Scenes/Smart target list scene/Cell/SmartTargetTableViewCell.swift
  Map/Scenes/Smart target list scene/Detail target scene/DetailTargetViewController.swift
  Map/Scenes/Smart target list scene/Detail target scene/View/Slider+EditableAddressView.swift
  Map/Scenes/Smart target list scene/SmartTargetListViewController.swift
  Map/Scenes/Smart target list scene/View/EmptyView.swift
Labels: bug

#146 (AKA-80) Фикс краша при нажатии на current location
  Map/Scenes/Map scene/MapViewController+MKMapViewDelegate.swift
Labels: bug

#147 (AKA-82) Проверка на максимальное количество отслеживаемых регионов
  Map/Business layer/Alerts.swift
  Map/Business layer/Constants.swift
  Map/Scenes/Map scene/MapInteractor.swift
  Map/Scenes/Map scene/MapModels.swift
  Map/Scenes/Map scene/MapPresenter.swift
  Map/Scenes/Map scene/MapViewController+MKMapViewDelegate.swift
  Map/Scenes/Map scene/MapViewController+MapDisplayLogic.swift
  Map/Scenes/Map scene/MapViewController.swift
Labels: enhancement
